### PR TITLE
added two new contributing files

### PR DESCRIPTION
**Pull request by tomassirio**

### CODE REVIEW

**Comment by o-leolleo** [comment]
Hey, the changes are great, thank you! 

What do you think of putting a link to the CONTRIBUTING.md in the README.md? It could be in a specific section like "looking to contribute?". Also, if you think it's interesting enough, you could add a section on how to run the project, and I can help here.

Anyway, if you don't feel like working on these suggestions, I can open an issue for each one, just let me know and I'll accept this PR or wait for the changes :D .

**Comment by tomassirio** [comment]
Open the issue and link me to it. I'm just waking up but I'm thrilled with hacktoberfest hahah

**Comment by o-leolleo** [comment]
@tomassirio that's great!

**Comment by o-leolleo** [comment]
@tomassirio it's there #4 \o

**Pull request merged**
